# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-HG4o3ZZxxnas6uysqisw8fg2JW-rkg
"""

import pandas as pd

def in_(sub_strs, str_):
  for sub_str in sub_strs:
    if sub_str.lower() in str_.lower():
      return True
  return False

def flatten_series(nestered_series):
  flat_list = []
  for element in nestered_series:
    if isinstance(element, list):
      flat_list.extend(flatten_series(element))
    else:
      flat_list.append(element)
  return pd.Series(flat_list)